/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserConfigRouteImport } from './routes/user-config'
import { Route as SneakersRouteImport } from './routes/sneakers'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AllProductsRouteImport } from './routes/all-products'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SneakersSneakerIdRouteImport } from './routes/sneakers.$sneakerId'
import { Route as CategorySportRouteImport } from './routes/category.$sport'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthSigninRouteImport } from './routes/auth.signin'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories/index'
import { Route as AdminSneakersCreateRouteImport } from './routes/admin/sneakers/create'
import { Route as AdminSneakersSneakerIdEditRouteImport } from './routes/admin/sneakers/$sneakerId/edit'
import { Route as AdminCategoriesCategoryIdEditRouteImport } from './routes/admin/categories/$categoryId/edit'

const MyOrdersLazyRouteImport = createFileRoute('/my-orders')()
const ForgotPasswordLazyRouteImport = createFileRoute('/forgot-password')()
const CheckoutLazyRouteImport = createFileRoute('/checkout')()
const AdminLazyRouteImport = createFileRoute('/admin')()
const AdminSneakersIndexLazyRouteImport = createFileRoute('/admin/sneakers/')()
const AdminBrandsIndexLazyRouteImport = createFileRoute('/admin/brands/')()
const AdminDashboardCreateLazyRouteImport = createFileRoute(
  '/admin/dashboard/create',
)()
const AdminCategoriesCreateLazyRouteImport = createFileRoute(
  '/admin/categories/create',
)()
const AdminBrandsEditLazyRouteImport = createFileRoute('/admin/brands/edit')()
const AdminBrandsCreateLazyRouteImport = createFileRoute(
  '/admin/brands/create',
)()
const AdminDashboardEditIdLazyRouteImport = createFileRoute(
  '/admin/dashboard/edit/$id',
)()

const MyOrdersLazyRoute = MyOrdersLazyRouteImport.update({
  id: '/my-orders',
  path: '/my-orders',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/my-orders.lazy').then((d) => d.Route))
const ForgotPasswordLazyRoute = ForgotPasswordLazyRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/forgot-password.lazy').then((d) => d.Route),
)
const CheckoutLazyRoute = CheckoutLazyRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/checkout.lazy').then((d) => d.Route))
const AdminLazyRoute = AdminLazyRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.lazy').then((d) => d.Route))
const UserConfigRoute = UserConfigRouteImport.update({
  id: '/user-config',
  path: '/user-config',
  getParentRoute: () => rootRouteImport,
} as any)
const SneakersRoute = SneakersRouteImport.update({
  id: '/sneakers',
  path: '/sneakers',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AllProductsRoute = AllProductsRouteImport.update({
  id: '/all-products',
  path: '/all-products',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SneakersSneakerIdRoute = SneakersSneakerIdRouteImport.update({
  id: '/$sneakerId',
  path: '/$sneakerId',
  getParentRoute: () => SneakersRoute,
} as any)
const CategorySportRoute = CategorySportRouteImport.update({
  id: '/category/$sport',
  path: '/category/$sport',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminLazyRoute,
} as any)
const AdminSneakersIndexLazyRoute = AdminSneakersIndexLazyRouteImport.update({
  id: '/sneakers/',
  path: '/sneakers/',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() =>
  import('./routes/admin/sneakers/index.lazy').then((d) => d.Route),
)
const AdminBrandsIndexLazyRoute = AdminBrandsIndexLazyRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() =>
  import('./routes/admin/brands/index.lazy').then((d) => d.Route),
)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() =>
  import('./routes/admin/categories/index.lazy').then((d) => d.Route),
)
const AdminDashboardCreateLazyRoute =
  AdminDashboardCreateLazyRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AdminDashboardRoute,
  } as any).lazy(() =>
    import('./routes/admin/dashboard/create.lazy').then((d) => d.Route),
  )
const AdminCategoriesCreateLazyRoute =
  AdminCategoriesCreateLazyRouteImport.update({
    id: '/categories/create',
    path: '/categories/create',
    getParentRoute: () => AdminLazyRoute,
  } as any).lazy(() =>
    import('./routes/admin/categories/create.lazy').then((d) => d.Route),
  )
const AdminBrandsEditLazyRoute = AdminBrandsEditLazyRouteImport.update({
  id: '/brands/edit',
  path: '/brands/edit',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() =>
  import('./routes/admin/brands/edit.lazy').then((d) => d.Route),
)
const AdminBrandsCreateLazyRoute = AdminBrandsCreateLazyRouteImport.update({
  id: '/brands/create',
  path: '/brands/create',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() =>
  import('./routes/admin/brands/create.lazy').then((d) => d.Route),
)
const AdminSneakersCreateRoute = AdminSneakersCreateRouteImport.update({
  id: '/sneakers/create',
  path: '/sneakers/create',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() =>
  import('./routes/admin/sneakers/create.lazy').then((d) => d.Route),
)
const AdminDashboardEditIdLazyRoute =
  AdminDashboardEditIdLazyRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AdminDashboardRoute,
  } as any).lazy(() =>
    import('./routes/admin/dashboard/edit.$id.lazy').then((d) => d.Route),
  )
const AdminSneakersSneakerIdEditRoute =
  AdminSneakersSneakerIdEditRouteImport.update({
    id: '/sneakers/$sneakerId/edit',
    path: '/sneakers/$sneakerId/edit',
    getParentRoute: () => AdminLazyRoute,
  } as any).lazy(() =>
    import('./routes/admin/sneakers/$sneakerId/edit.lazy').then((d) => d.Route),
  )
const AdminCategoriesCategoryIdEditRoute =
  AdminCategoriesCategoryIdEditRouteImport.update({
    id: '/categories/$categoryId/edit',
    path: '/categories/$categoryId/edit',
    getParentRoute: () => AdminLazyRoute,
  } as any).lazy(() =>
    import('./routes/admin/categories/$categoryId/edit.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/all-products': typeof AllProductsRoute
  '/auth': typeof AuthRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/sneakers': typeof SneakersRouteWithChildren
  '/user-config': typeof UserConfigRoute
  '/admin': typeof AdminLazyRouteWithChildren
  '/checkout': typeof CheckoutLazyRoute
  '/forgot-password': typeof ForgotPasswordLazyRoute
  '/my-orders': typeof MyOrdersLazyRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/category/$sport': typeof CategorySportRoute
  '/sneakers/$sneakerId': typeof SneakersSneakerIdRoute
  '/admin/sneakers/create': typeof AdminSneakersCreateRoute
  '/admin/brands/create': typeof AdminBrandsCreateLazyRoute
  '/admin/brands/edit': typeof AdminBrandsEditLazyRoute
  '/admin/categories/create': typeof AdminCategoriesCreateLazyRoute
  '/admin/dashboard/create': typeof AdminDashboardCreateLazyRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/brands': typeof AdminBrandsIndexLazyRoute
  '/admin/sneakers': typeof AdminSneakersIndexLazyRoute
  '/admin/categories/$categoryId/edit': typeof AdminCategoriesCategoryIdEditRoute
  '/admin/sneakers/$sneakerId/edit': typeof AdminSneakersSneakerIdEditRoute
  '/admin/dashboard/edit/$id': typeof AdminDashboardEditIdLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/all-products': typeof AllProductsRoute
  '/auth': typeof AuthRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/sneakers': typeof SneakersRouteWithChildren
  '/user-config': typeof UserConfigRoute
  '/admin': typeof AdminLazyRouteWithChildren
  '/checkout': typeof CheckoutLazyRoute
  '/forgot-password': typeof ForgotPasswordLazyRoute
  '/my-orders': typeof MyOrdersLazyRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/category/$sport': typeof CategorySportRoute
  '/sneakers/$sneakerId': typeof SneakersSneakerIdRoute
  '/admin/sneakers/create': typeof AdminSneakersCreateRoute
  '/admin/brands/create': typeof AdminBrandsCreateLazyRoute
  '/admin/brands/edit': typeof AdminBrandsEditLazyRoute
  '/admin/categories/create': typeof AdminCategoriesCreateLazyRoute
  '/admin/dashboard/create': typeof AdminDashboardCreateLazyRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/brands': typeof AdminBrandsIndexLazyRoute
  '/admin/sneakers': typeof AdminSneakersIndexLazyRoute
  '/admin/categories/$categoryId/edit': typeof AdminCategoriesCategoryIdEditRoute
  '/admin/sneakers/$sneakerId/edit': typeof AdminSneakersSneakerIdEditRoute
  '/admin/dashboard/edit/$id': typeof AdminDashboardEditIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/all-products': typeof AllProductsRoute
  '/auth': typeof AuthRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/sneakers': typeof SneakersRouteWithChildren
  '/user-config': typeof UserConfigRoute
  '/admin': typeof AdminLazyRouteWithChildren
  '/checkout': typeof CheckoutLazyRoute
  '/forgot-password': typeof ForgotPasswordLazyRoute
  '/my-orders': typeof MyOrdersLazyRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/category/$sport': typeof CategorySportRoute
  '/sneakers/$sneakerId': typeof SneakersSneakerIdRoute
  '/admin/sneakers/create': typeof AdminSneakersCreateRoute
  '/admin/brands/create': typeof AdminBrandsCreateLazyRoute
  '/admin/brands/edit': typeof AdminBrandsEditLazyRoute
  '/admin/categories/create': typeof AdminCategoriesCreateLazyRoute
  '/admin/dashboard/create': typeof AdminDashboardCreateLazyRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/brands/': typeof AdminBrandsIndexLazyRoute
  '/admin/sneakers/': typeof AdminSneakersIndexLazyRoute
  '/admin/categories/$categoryId/edit': typeof AdminCategoriesCategoryIdEditRoute
  '/admin/sneakers/$sneakerId/edit': typeof AdminSneakersSneakerIdEditRoute
  '/admin/dashboard/edit/$id': typeof AdminDashboardEditIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/all-products'
    | '/auth'
    | '/favorites'
    | '/sneakers'
    | '/user-config'
    | '/admin'
    | '/checkout'
    | '/forgot-password'
    | '/my-orders'
    | '/admin/dashboard'
    | '/auth/signin'
    | '/auth/signup'
    | '/category/$sport'
    | '/sneakers/$sneakerId'
    | '/admin/sneakers/create'
    | '/admin/brands/create'
    | '/admin/brands/edit'
    | '/admin/categories/create'
    | '/admin/dashboard/create'
    | '/admin/categories'
    | '/admin/dashboard/'
    | '/admin/brands'
    | '/admin/sneakers'
    | '/admin/categories/$categoryId/edit'
    | '/admin/sneakers/$sneakerId/edit'
    | '/admin/dashboard/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/all-products'
    | '/auth'
    | '/favorites'
    | '/sneakers'
    | '/user-config'
    | '/admin'
    | '/checkout'
    | '/forgot-password'
    | '/my-orders'
    | '/auth/signin'
    | '/auth/signup'
    | '/category/$sport'
    | '/sneakers/$sneakerId'
    | '/admin/sneakers/create'
    | '/admin/brands/create'
    | '/admin/brands/edit'
    | '/admin/categories/create'
    | '/admin/dashboard/create'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/brands'
    | '/admin/sneakers'
    | '/admin/categories/$categoryId/edit'
    | '/admin/sneakers/$sneakerId/edit'
    | '/admin/dashboard/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/all-products'
    | '/auth'
    | '/favorites'
    | '/sneakers'
    | '/user-config'
    | '/admin'
    | '/checkout'
    | '/forgot-password'
    | '/my-orders'
    | '/admin/dashboard'
    | '/auth/signin'
    | '/auth/signup'
    | '/category/$sport'
    | '/sneakers/$sneakerId'
    | '/admin/sneakers/create'
    | '/admin/brands/create'
    | '/admin/brands/edit'
    | '/admin/categories/create'
    | '/admin/dashboard/create'
    | '/admin/categories/'
    | '/admin/dashboard/'
    | '/admin/brands/'
    | '/admin/sneakers/'
    | '/admin/categories/$categoryId/edit'
    | '/admin/sneakers/$sneakerId/edit'
    | '/admin/dashboard/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllProductsRoute: typeof AllProductsRoute
  AuthRoute: typeof AuthRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  SneakersRoute: typeof SneakersRouteWithChildren
  UserConfigRoute: typeof UserConfigRoute
  AdminLazyRoute: typeof AdminLazyRouteWithChildren
  CheckoutLazyRoute: typeof CheckoutLazyRoute
  ForgotPasswordLazyRoute: typeof ForgotPasswordLazyRoute
  MyOrdersLazyRoute: typeof MyOrdersLazyRoute
  CategorySportRoute: typeof CategorySportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-orders': {
      id: '/my-orders'
      path: '/my-orders'
      fullPath: '/my-orders'
      preLoaderRoute: typeof MyOrdersLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-config': {
      id: '/user-config'
      path: '/user-config'
      fullPath: '/user-config'
      preLoaderRoute: typeof UserConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sneakers': {
      id: '/sneakers'
      path: '/sneakers'
      fullPath: '/sneakers'
      preLoaderRoute: typeof SneakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-products': {
      id: '/all-products'
      path: '/all-products'
      fullPath: '/all-products'
      preLoaderRoute: typeof AllProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sneakers/$sneakerId': {
      id: '/sneakers/$sneakerId'
      path: '/$sneakerId'
      fullPath: '/sneakers/$sneakerId'
      preLoaderRoute: typeof SneakersSneakerIdRouteImport
      parentRoute: typeof SneakersRoute
    }
    '/category/$sport': {
      id: '/category/$sport'
      path: '/category/$sport'
      fullPath: '/category/$sport'
      preLoaderRoute: typeof CategorySportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/sneakers/': {
      id: '/admin/sneakers/'
      path: '/sneakers'
      fullPath: '/admin/sneakers'
      preLoaderRoute: typeof AdminSneakersIndexLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/brands/': {
      id: '/admin/brands/'
      path: '/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AdminBrandsIndexLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/dashboard/create': {
      id: '/admin/dashboard/create'
      path: '/create'
      fullPath: '/admin/dashboard/create'
      preLoaderRoute: typeof AdminDashboardCreateLazyRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/categories/create': {
      id: '/admin/categories/create'
      path: '/categories/create'
      fullPath: '/admin/categories/create'
      preLoaderRoute: typeof AdminCategoriesCreateLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/brands/edit': {
      id: '/admin/brands/edit'
      path: '/brands/edit'
      fullPath: '/admin/brands/edit'
      preLoaderRoute: typeof AdminBrandsEditLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/brands/create': {
      id: '/admin/brands/create'
      path: '/brands/create'
      fullPath: '/admin/brands/create'
      preLoaderRoute: typeof AdminBrandsCreateLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/sneakers/create': {
      id: '/admin/sneakers/create'
      path: '/sneakers/create'
      fullPath: '/admin/sneakers/create'
      preLoaderRoute: typeof AdminSneakersCreateRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/dashboard/edit/$id': {
      id: '/admin/dashboard/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/dashboard/edit/$id'
      preLoaderRoute: typeof AdminDashboardEditIdLazyRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/sneakers/$sneakerId/edit': {
      id: '/admin/sneakers/$sneakerId/edit'
      path: '/sneakers/$sneakerId/edit'
      fullPath: '/admin/sneakers/$sneakerId/edit'
      preLoaderRoute: typeof AdminSneakersSneakerIdEditRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/categories/$categoryId/edit': {
      id: '/admin/categories/$categoryId/edit'
      path: '/categories/$categoryId/edit'
      fullPath: '/admin/categories/$categoryId/edit'
      preLoaderRoute: typeof AdminCategoriesCategoryIdEditRouteImport
      parentRoute: typeof AdminLazyRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface SneakersRouteChildren {
  SneakersSneakerIdRoute: typeof SneakersSneakerIdRoute
}

const SneakersRouteChildren: SneakersRouteChildren = {
  SneakersSneakerIdRoute: SneakersSneakerIdRoute,
}

const SneakersRouteWithChildren = SneakersRoute._addFileChildren(
  SneakersRouteChildren,
)

interface AdminDashboardRouteChildren {
  AdminDashboardCreateLazyRoute: typeof AdminDashboardCreateLazyRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminDashboardEditIdLazyRoute: typeof AdminDashboardEditIdLazyRoute
}

const AdminDashboardRouteChildren: AdminDashboardRouteChildren = {
  AdminDashboardCreateLazyRoute: AdminDashboardCreateLazyRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminDashboardEditIdLazyRoute: AdminDashboardEditIdLazyRoute,
}

const AdminDashboardRouteWithChildren = AdminDashboardRoute._addFileChildren(
  AdminDashboardRouteChildren,
)

interface AdminLazyRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRouteWithChildren
  AdminSneakersCreateRoute: typeof AdminSneakersCreateRoute
  AdminBrandsCreateLazyRoute: typeof AdminBrandsCreateLazyRoute
  AdminBrandsEditLazyRoute: typeof AdminBrandsEditLazyRoute
  AdminCategoriesCreateLazyRoute: typeof AdminCategoriesCreateLazyRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminBrandsIndexLazyRoute: typeof AdminBrandsIndexLazyRoute
  AdminSneakersIndexLazyRoute: typeof AdminSneakersIndexLazyRoute
  AdminCategoriesCategoryIdEditRoute: typeof AdminCategoriesCategoryIdEditRoute
  AdminSneakersSneakerIdEditRoute: typeof AdminSneakersSneakerIdEditRoute
}

const AdminLazyRouteChildren: AdminLazyRouteChildren = {
  AdminDashboardRoute: AdminDashboardRouteWithChildren,
  AdminSneakersCreateRoute: AdminSneakersCreateRoute,
  AdminBrandsCreateLazyRoute: AdminBrandsCreateLazyRoute,
  AdminBrandsEditLazyRoute: AdminBrandsEditLazyRoute,
  AdminCategoriesCreateLazyRoute: AdminCategoriesCreateLazyRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminBrandsIndexLazyRoute: AdminBrandsIndexLazyRoute,
  AdminSneakersIndexLazyRoute: AdminSneakersIndexLazyRoute,
  AdminCategoriesCategoryIdEditRoute: AdminCategoriesCategoryIdEditRoute,
  AdminSneakersSneakerIdEditRoute: AdminSneakersSneakerIdEditRoute,
}

const AdminLazyRouteWithChildren = AdminLazyRoute._addFileChildren(
  AdminLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllProductsRoute: AllProductsRoute,
  AuthRoute: AuthRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  SneakersRoute: SneakersRouteWithChildren,
  UserConfigRoute: UserConfigRoute,
  AdminLazyRoute: AdminLazyRouteWithChildren,
  CheckoutLazyRoute: CheckoutLazyRoute,
  ForgotPasswordLazyRoute: ForgotPasswordLazyRoute,
  MyOrdersLazyRoute: MyOrdersLazyRoute,
  CategorySportRoute: CategorySportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
