/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SneakersRouteImport } from './routes/sneakers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SneakersSneakerIdRouteImport } from './routes/sneakers.$sneakerId'
import { Route as CategorySportRouteImport } from './routes/category.$sport'

const SneakersRoute = SneakersRouteImport.update({
  id: '/sneakers',
  path: '/sneakers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SneakersSneakerIdRoute = SneakersSneakerIdRouteImport.update({
  id: '/$sneakerId',
  path: '/$sneakerId',
  getParentRoute: () => SneakersRoute,
} as any)
const CategorySportRoute = CategorySportRouteImport.update({
  id: '/category/$sport',
  path: '/category/$sport',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sneakers': typeof SneakersRouteWithChildren
  '/category/$sport': typeof CategorySportRoute
  '/sneakers/$sneakerId': typeof SneakersSneakerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sneakers': typeof SneakersRouteWithChildren
  '/category/$sport': typeof CategorySportRoute
  '/sneakers/$sneakerId': typeof SneakersSneakerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sneakers': typeof SneakersRouteWithChildren
  '/category/$sport': typeof CategorySportRoute
  '/sneakers/$sneakerId': typeof SneakersSneakerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sneakers' | '/category/$sport' | '/sneakers/$sneakerId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sneakers' | '/category/$sport' | '/sneakers/$sneakerId'
  id:
    | '__root__'
    | '/'
    | '/sneakers'
    | '/category/$sport'
    | '/sneakers/$sneakerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SneakersRoute: typeof SneakersRouteWithChildren
  CategorySportRoute: typeof CategorySportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sneakers': {
      id: '/sneakers'
      path: '/sneakers'
      fullPath: '/sneakers'
      preLoaderRoute: typeof SneakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sneakers/$sneakerId': {
      id: '/sneakers/$sneakerId'
      path: '/$sneakerId'
      fullPath: '/sneakers/$sneakerId'
      preLoaderRoute: typeof SneakersSneakerIdRouteImport
      parentRoute: typeof SneakersRoute
    }
    '/category/$sport': {
      id: '/category/$sport'
      path: '/category/$sport'
      fullPath: '/category/$sport'
      preLoaderRoute: typeof CategorySportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SneakersRouteChildren {
  SneakersSneakerIdRoute: typeof SneakersSneakerIdRoute
}

const SneakersRouteChildren: SneakersRouteChildren = {
  SneakersSneakerIdRoute: SneakersSneakerIdRoute,
}

const SneakersRouteWithChildren = SneakersRoute._addFileChildren(
  SneakersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SneakersRoute: SneakersRouteWithChildren,
  CategorySportRoute: CategorySportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
